services:
  postgres:
    image: postgres:14
    container_name: netflix-postgres
    environment:
      POSTGRES_DB: netflix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/src/main/resources/schema-postgres.sql:/docker-entrypoint-initdb.d/schema-postgres.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: netflix-backend
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env.development
    volumes:
      - ./backend:/app/backend

volumes:
  pgdata:
