[build]
  base = "frontend"
  command = "CI=false npm run build"
  publish = "build"

[context.production.environment]
  REACT_APP_API_URL = "https://netflix-dmqv.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200