services:
  - type: web
    name: netflix-backend
    env: docker
    buildCommand: docker build -t netflix-app .
    startCommand: docker run -p $PORT:8080 
      -e MYSQL_URL="jdbc:${MYSQL_URL}" 
      -e MYSQL_USERNAME="${MYSQL_USERNAME}" 
      -e MYSQL_PASSWORD="${MYSQL_PASSWORD}"
      -e SPRING_PROFILES_ACTIVE="prod"
      netflix-app
    envVars:
      - key: MYSQL_URL
        value: jdbc:${MYSQL_URL}
      - key: MYSQL_USERNAME
        value: ${MYSQL_USERNAME}
      - key: MYSQL_PASSWORD
        value: ${MYSQL_PASSWORD}