services:
  - type: web
    name: netflix-backend
    env: docker
    buildCommand: docker build -t netflix-app .
    startCommand: docker run -p $PORT:8080 
      -e MYSQL_URL="${MYSQL_URL}" 
      -e MYSQL_USERNAME="${MYSQL_USERNAME}" 
      -e MYSQL_PASSWORD="${MYSQL_PASSWORD}"
      -e SPRING_PROFILES_ACTIVE="prod"
      netflix-app
    envVars:
      - key: PORT
        sync: false
        value: 8080
      - key: MYSQL_URL
        sync: false
      - key: MYSQL_USERNAME
        sync: false  
      - key: MYSQL_PASSWORD
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true