services:
  - type: web
    name: netflix-backend
    env: docker
    buildCommand: docker build -t netflix-app .
    startCommand: >
      docker run -p $PORT:8080
      -e POSTGRES_DB="${POSTGRES_DB}"
      -e POSTGRES_USER="${POSTGRES_USER}"
      -e POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
      -e SPRING_PROFILES_ACTIVE="prod"
      netflix-app
    envVars:
      - key: PORT
        value: 8080
      - key: POSTGRES_DB
        value: jdbc:postgresql://<FLY_PG_HOST>:5432/<DB_NAME>
      - key: POSTGRES_USER
        value: <FLY_PG_USER>
      - key: POSTGRES_PASSWORD
        value: <FLY_PG_PASSWORD>
    autoDeploy: true
