spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
server:
  port: ${PORT:8080}