spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  mvc:
    servlet:
      load-on-startup: 1
server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

mybatis:
  configuration:
    map-underscore-to-camel-case: true