spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  web:
    resources:
      static-locations: file:/app/frontend/build/
      add-mappings: true
  mvc:
    view:
      prefix: ""
      suffix: ""
    static-path-pattern: /**
  resources:
    static-locations: file:/app/static/
    add-mappings: false
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-postgres.sql
      continue-on-error: true

logging:
  level:
    root: INFO
    com.mysite: DEBUG # 네 패키지 전체 DEBUG
    org.mybatis: DEBUG
    org.apache.ibatis: DEBUG
    java.sql: DEBUG
    javax.sql: DEBUG
---
spring:
  config:
    import: optional:file:local.env[.properties]
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-postgres.sql
      continue-on-error: true

server:
  address: 0.0.0.0
  port: ${PORT:8080}

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: true

server:
  port: ${PORT:8080}
