spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  mvc:
    cors:
      allowed-origins: "https://net-flix-clone-dahee-kim.netlify.app,http://localhost:3000"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS,HEAD,PATCH"
      allowed-headers: "*"
      exposed-headers: "Access-Control-Allow-Origin,Access-Control-Allow-Credentials,Authorization"
      allow-credentials: true
      max-age: 3600
server:
  port: ${PORT:8080}
  servlet:
    context-path: /api