spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
server:
  port: ${PORT:8080}

mybatis:
  configuration:
    map-underscore-to-camel-case: true