spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  mvc:
    view:
      prefix: /static/
      suffix: .html
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true
      cache:
        period: 0
  resources:
    static-locations: classpath:/static/
    add-mappings: true
    chain:
      strategy:
        content:
          enabled: true
          paths: /**

mybatis:
  type-aliases-package: com.mysite.netflixProject
  configuration:
    map-underscore-to-camel-case: true

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: true
server:
  port: ${PORT:8080}

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: true
server:
  port: ${PORT:8080}